name: Deploy Agent Platform to EC2
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Create PM2 ecosystem file
        run: |
          cat << EOF > ecosystem.config.js
          module.exports = {
            apps : [{
              name: "agent-chat",
              script: "npm",
              args: "start",
              env: {
                NODE_ENV: "production",
                PORT: 3001
              },
            }]
          }
          EOF

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r .next package.json package-lock.json ecosystem.config.js matcha@${{ secrets.SSH_HOST }}:~/agent-platform
          ssh -o StrictHostKeyChecking=no -i private_key.pem matcha@${{ secrets.SSH_HOST }} << 'EOF'
            set -x
            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # Install Node.js 18 if not already installed
            nvm install 18
            nvm use 18
            # Verify Node.js version
            node -v
            # Install PM2 globally
            npm install -g pm2
            # Add npm global bin to PATH
            export PATH="$HOME/.npm-global/bin:$PATH"
            cd ~/agent-platform
            npm ci --only=production
            pm2 delete agent-chat || true
            pm2 start ecosystem.config.js
            pm2 save
            # Generate startup script
            pm2 startup systemd -u matcha --hp /home/matcha | tail -n 1 > startup_script.sh
            chmod +x startup_script.sh
            ./startup_script.sh
            pm2 save
          EOF